version: '3.9'

services:

  mysql-master:
    image: mysql:latest
    volumes:
      - ./data/master:/var/lib/mysql
      - ./conf/master.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $MASTER_ROOT_PASSWORD
    ports:
      - 3300:3306
    networks:
      - mysql-network

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql-master
    volumes:
      - ./data/backup:/backup
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=${USER_SUPER_USERNAME}
      - MYSQL_PASS=${USER_SUPER_PASSWORD}
      - MAX_BACKUPS=4
      - INIT_BACKUP=0
      - CRON_TIME=0 */6 * * *
    networks:
      - mysql-network
      
networks:
  mysql-network:
    external: true