version: '3.9'

services:

  mysql-slave2:
    image: mysql:latest
    volumes:
      - ./data/slave2:/var/lib/mysql
      - ./hosts/master-slave/slave2.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $SLAVE2_ROOT_PASSWORD
    ports:
      - 3302:3306
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true