version: '3.7'

services:
  mysql-master:
    container_name: $FIRST_HOST
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./data/master1:/var/lib/mysql
      - ./hosts/master-master/server1.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: Asia/jakarta
      MYSQL_ROOT_PASSWORD: $FIRST_ROOT_PASSWORD
    ports:
      - 3006:3306
    networks:
      - mysql-network

  mysql-master2:
    container_name: $SECOND_HOST
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./data/master2:/var/lib/mysql
      - ./hosts/master-master/server2.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $SECOND_ROOT_PASSWORD
    ports:
      - 3007:3306
    networks:
      - mysql-network
  
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - proxysql
    container_name: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - TZ=Asia/Jakarta
      - PMA_HOST=proxysql
      - PMA_PORT=6033
      - UPLOAD_LIMIT=2G
      - MEMORY_LIMIT=500M
      - MAX_EXECUTION_TIME=1000
    networks:
      - mysql-network
      
  mysql-cron-backup:
    depends_on:
      - mysql-master
    image: fradelg/mysql-cron-backup
    container_name: mysql-cron-backup
    restart: unless-stopped    
    volumes:
      - ./data/backup:/backup
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=root
      - MYSQL_PASS=${FIRST_ROOT_PASSWORD}
      - MAX_BACKUPS=4
      - INIT_BACKUP=0
      - CRON_TIME=0 */6 * * *
    networks:
      - mysql-network

  proxysql:
    image: proxysql/proxysql
    depends_on:
      - mysql-master
      - mysql-master2
    ports:
      - 6032:6032
      - 6033:6033
    restart: unless-stopped
    volumes:
      - ./proxysql/master-master/proxysql.cnf:/etc/proxysql.cnf
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true