version: '3'

services:
  mysql-master:
    container_name: $FIRST_DB_NAME
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - '/var/lib/mysql/master:/var/lib/mysql'
      - './first-host.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: $FIRST_ROOT_PASSWORD
    ports:
      - "$IP_ADDR:3306:3306"
    networks:
      - db-replication

  mysql-slave:
    container_name: $SECOND_DB_NAME
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - '/var/lib/mysql/slave:/var/lib/mysql'
      - './second-host.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: $SECOND_ROOT_PASSWORD
    ports:
      - "$IP_ADDR:3307:3306"
    networks:
      - db-replication
      
networks:
  db-replication:
    name: db-replication
    driver: bridge
