version: '3.9'

services:
  mysql-master:
    image: mysql:latest
    volumes:
      - ./data/master:/var/lib/mysql
      - ./hosts/master-slave/server1.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: Asia/jakarta
      MYSQL_ROOT_PASSWORD: $FIRST_ROOT_PASSWORD
    ports:
      - 3006:3306
    networks:
      - mysql-network

  mysql-slave:
    image: mysql:latest
    volumes:
      - ./data/slave:/var/lib/mysql
      - ./hosts/master-slave/server2.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: "Asia/jakarta"
      MYSQL_ROOT_PASSWORD: $SECOND_ROOT_PASSWORD
    ports:
      - 3007:3306
    networks:
      - mysql-network

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql-master
    volumes:
      - ./data/backup:/backup
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=root
      - MYSQL_PASS=${FIRST_ROOT_PASSWORD}
      - MAX_BACKUPS=4
      - INIT_BACKUP=0
      - CRON_TIME=0 */6 * * *
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true