version: '3.7'

services:
  mysql-master:
    container_name: $HOST_MASTER
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./data/master1:/var/lib/mysql
      - ./hosts/master-master/server1.cnf:/etc/mysql/conf.d/mysql.cnf
    command: bash -c "chmod 644 /etc/mysql/conf.d/mysql.cnf && docker-entrypoint.sh mysqld"
    environment:
      TZ: Asia/jakarta
      MASTER_ROOT_PASSWORD: $FIRST_ROOT_PASSWORD
    ports:
      - 3006:3306
    networks:
      - mysql-network
      
  mysql-cron-backup:
    depends_on:
      - mysql-master
    image: fradelg/mysql-cron-backup
    container_name: mysql-cron-backup
    restart: unless-stopped    
    volumes:
      - ./data/backup:/backup
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=root
      - MYSQL_PASS=${FIRST_ROOT_PASSWORD}
      - MAX_BACKUPS=4
      - INIT_BACKUP=0
      - CRON_TIME=0 */6 * * *
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true